name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        swift:
          - image: "swift:5.9-jammy"
            os: ubuntu-22.04
          - image: "swift:5.10-jammy"
            os: ubuntu-22.04
          - image: "swift:5.10-noble"
            os: ubuntu-24.04
          - image: "swift:6.0-noble"
            os: ubuntu-24.04
          - image: "swift:6.1-jammy"
            os: ubuntu-22.04
          - image: "swift:6.1-noble"
            os: ubuntu-24.04
          - image: "swift:6.2-jammy"
            os: ubuntu-22.04
          - image: "swift:6.2-noble"
            os: ubuntu-24.04
          - image: "swift:6.3-jammy"
            os: ubuntu-22.04
          - image: "swift:6.3-noble"
            os: ubuntu-24.04
    name: Linux
    runs-on: ${{ matrix.swift.os }}
    container:
      image: ${{ matrix.swift.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -v -c debug
    - name: Test
      run: swift test -c debug --parallel

  android:
    name: Android
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build for Android
      uses: skiptools/swift-android-action@v2
      with:
        swift-version: "6.3"

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Setup Swift on Windows"
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.3-release
          tag: 6.3-RELEASE
      - name: "Test Swift Package on Windows"
        run: swift test

  apple:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        xcode:
          - version: "26.4"
            runner: macos-26
            platform: "macOS"
            arch: "arm64"
          - version: "16.4"
            runner: macos-15
            platform: "macOS"
            arch: "arm64"
          - version: "15.4"
            runner: macos-14
            platform: "macOS"
            arch: "arm64"
          - version: "26.4"
            runner: macos-26
            platform: "macOS"
            arch: "arm64"
            variant: "Mac Catalyst"
          - version: "16.4"
            runner: macos-15
            platform: "macOS"
            arch: "arm64"
            variant: "Mac Catalyst"
          - version: "15.4"
            runner: macos-14
            platform: "macOS"
            arch: "arm64"
            variant: "Mac Catalyst"
          - version: "26.4"
            runner: macos-26
            platform: "iOS"
            simulator: "iPhone 17,OS=26.4"
          - version: "16.4"
            runner: macos-15
            platform: "iOS"
            simulator: "iPhone 16,OS=18.5"
          - version: "15.4"
            runner: macos-14
            platform: "iOS"
            simulator: "iPhone 15,OS=17.5"
          - version: "26.4"
            runner: macos-26
            platform: "watchOS"
            simulator: "Apple Watch Series 11 (46mm),OS=26.4"
          - version: "16.4"
            runner: macos-15
            platform: "watchOS"
            simulator: "Apple Watch Series 10 (46mm),OS=11.5"
          - version: "15.4"
            runner: macos-14
            platform: "watchOS"
            simulator: "Apple Watch Series 9 (45mm),OS=10.5"
          - version: "26.4"
            runner: macos-26
            platform: "tvOS"
            simulator: "Apple TV 4K (3rd generation),OS=26.4"
          - version: "16.4"
            runner: macos-15
            platform: "tvOS"
            simulator: "Apple TV 4K (3rd generation),OS=18.5"
          - version: "15.4"
            runner: macos-14
            platform: "tvOS"
            simulator: "Apple TV 4K (3rd generation),OS=17.5"
          - version: "26.4"
            runner: macos-26
            platform: "visionOS"
            simulator: "Apple Vision Pro,OS=26.4"
          - version: "16.4"
            runner: macos-15
            platform: "visionOS"
            simulator: "Apple Vision Pro,OS=2.5"
          - version: "15.4"
            runner: macos-14
            platform: "visionOS"
            simulator: "Apple Vision Pro,OS=1.2"
    name: Apple
    runs-on: ${{ matrix.xcode.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode
      run: xcodes select ${{ matrix.xcode.version }}
    - name: Swift Version
      run: swift --version
    - name: Build (macOS)
      if: matrix.xcode.platform == 'macOS' && matrix.xcode.variant != 'Mac Catalyst'
      run: |
        swift build -v -c debug
        xcodebuild -scheme Queuer -destination "platform=${{ matrix.xcode.platform }},arch=${{ matrix.xcode.arch }}"
    - name: Test (macOS)
      if: matrix.xcode.platform == 'macOS' && matrix.xcode.variant != 'Mac Catalyst'
      run: |
        swift test -c debug --parallel
        xcodebuild -scheme Queuer -destination "platform=${{ matrix.xcode.platform }},arch=${{ matrix.xcode.arch }}" -testenv GITHUB_RUN_ID=$GITHUB_RUN_ID test
    - name: Build (Mac Catalyst)
      if: matrix.xcode.variant == 'Mac Catalyst'
      run: xcodebuild -scheme Queuer -destination "platform=${{ matrix.xcode.platform }},arch=${{ matrix.xcode.arch }},variant=${{ matrix.xcode.variant }}"
    - name: Test (Mac Catalyst)
      if: matrix.xcode.variant == 'Mac Catalyst'
      run: xcodebuild -scheme Queuer -destination "platform=${{ matrix.xcode.platform }},arch=${{ matrix.xcode.arch }},variant=${{ matrix.xcode.variant }}" -testenv GITHUB_RUN_ID=$GITHUB_RUN_ID test
    - name: Build (Simulator)
      if: matrix.xcode.platform != 'macOS'
      run: xcodebuild -scheme Queuer -destination "platform=${{ matrix.xcode.platform }} Simulator,name=${{ matrix.xcode.simulator }}"
    - name: Test (Simulator)
      if: matrix.xcode.platform != 'macOS'
      run: xcodebuild -scheme Queuer -destination "platform=${{ matrix.xcode.platform }} Simulator,name=${{ matrix.xcode.simulator }}" -testenv GITHUB_RUN_ID=$GITHUB_RUN_ID test
